### ISSUE TITLE
FEATURE: ODP Pathway: Landing Page: ODP Plus Service Page with Custom Onboarding to "activate"

### ISSUE THREAD

**Issue by davidcjanssens** [excelerate-america/ea-features#124]
# Landing Page: ODP Plus Service Page with Custom Onboarding to "activate"

## MILESTONES
- September 20th, 2022, Pathway Check-in 
- September 30th, 2022, Preview Landing Page
- September 23rd,  2022, Layout Handoff
- October 3rd, 2022, Design Handoff
- Internal Review : date?
- Content Hygraph Integration
- Launch
- November (End of Pitch) drive pitch participants to make ODP accounts

## OBJECTIVE
**Goal:** To amplify our **ODP express** service beyond benefits but still within plus.  To allow direct lead generation and custom onboarding for **ODP express.**  Members that activate this service also are given a sponsored plus account subscription level. 

**Business Scope:** focus on ODP express account creation 

**Required Feilds:**

- First Name 
- Last Name
- Phone Number
- Shipping Address

## DEPENDENCIES
- Discussion on 
- excelerate-america/ea-features#136 
- excelerate-america/ea-features#19 
- excelerate-america/ea-features#23 

## TERMS

** Starting Vendor Account**
```
businessAccount: {
   ...
   vendorAccounts: {

        ODP: { 
              vendorName: 'Office Depot Partners',
              vendorStatus: 'PENDING',
              vendorType: 'EXPRESS',
              vendorDescription: 'blah',
              vendorBusinessAccountId: '1234567',
              vendorEmail: 'lyndon@excelerateamerica.com'
         }, 
       VENDOR_CODE2: { ... }
        }
 }
```

** Activated Vendor Account**
```
businessAccount: {
   ...
   vendorAccounts: {

        ODP: {
            vendorAccountNumber: "123254635462351432edwqefgrwvrcax",
            vendorBusinessAccountCompany: "Bandhan Group Test",
            vendorBusinessAccountId:"1234567",
            vendorCode:"ODP",
            vendorDescription:"blah",
            vendorEmail:"lyndon@excelerateamerica.com",
            vendorName:"Office Depot Partners",
            vendorStatus:"CONNECTED",
            vendorType:"EXPRESS",
            vendorUsername:"lyndonODP",
        }
 }
```

**VendorAccount Status:**

- PENDING
- DISCONNECTED
- CONNECTED

**Request Status:**

- PROCESSING
- CLOSED
- OPEN

**Zendsell Intergraton**

Two Feilds are added to a business account, vendors pending and vendors connected 

![Image](https://user-images.githubusercontent.com/80287668/195438108-d52a2ae2-1fff-4a10-86a6-1637d825e363.png)

## QUESTIONS
- Considering this is an asynchronous process after member-plus click activate, what do we show the member? 
- How does the member know when the account is ready? 
- Where do they return to check status? What do they see before the account is active & then after the account is active?
- How do we handle the storing of the newly created account number / info on the business account?  with Elevate, the businessAccount record has a map field called vendorAccounts. which stores a vendorObject like the following:

**See Updated Structure in Terms**
~~{
    ODP: {
	vendorName: Office Depot,
        status: "PENDING",
	type: "BUSINESS",
        email: owner,
        vendorAccountId: vendorspecificid
	vendorDescription: "this is a OD portal account",
	businessAccountId: bizId,
        vendorUsername: fromVendor,
    },
    VENDOR_CODE2: { ... }
}~~

## TESTING

https://github.com/excelerate-america/ea-ecosystem-admin/tree/stg/functions/src/__tests__

_ TESTS_

1) Jest Tests are configured to run on both the local emulator and the staged environment
2) Use npm run test (requires npm run dev) or npm run test-stg respectively 

**To Create Accounts, Discord, Business Account and Members Accounts**
[account.test.ts](https://github.com/excelerate-america/ea-ecosystem-admin/blob/stg/functions/src/__tests__/account.test.ts)

**To test the building of membership preferences and a member RSVPing to an event, SendGrid email will also be triggered**
[event.test.ts](https://github.com/excelerate-america/ea-ecosystem-admin/blob/stg/functions/src/__tests__/event.test.ts)

**To Add an example of a second type of vendor account**
[addVendorSecond.test.ts](https://github.com/excelerate-america/ea-ecosystem-admin/blob/stg/functions/src/__tests__/addVendorSecond.test.ts)

**To Add an example of a vendor account**
[vendor.test.ts](https://github.com/excelerate-america/ea-ecosystem-admin/blob/stg/functions/src/__tests__/vendor.test.ts)

**To Add an example of a second type of vendor account**
[addVendorSecond.test.ts](https://github.com/excelerate-america/ea-ecosystem-admin/blob/stg/functions/src/__tests__/addVendorSecond.test.ts)

**To test the process of moving a request to 'Processing' which should result in an vendor account activation**
[change-request.test.ts](https://github.com/excelerate-america/ea-ecosystem-admin/blob/stg/functions/src/__tests__/change-request.test.ts)

## REQUIREMENTS

URL: /services/business-essentials
**P0**
### ADMIN APP
- Ability to create A GroupCode and PromoCode that is captured and retained throughout onboard process

### APP/SITE 
- A plus account who clicks activate Button go straight to a confirmation page ODP service request sent
- Remove ODP from the benefits section and adjust explore plus page
-  services/odp landing page that both public and members can view
   - Update Plus forms with new fields 
- Service will be Plus and shown in Nav under services
- ODP landing page will have
   - How it works section to highlight the program and benefits
   - Partner/brand logo section
   - Highlights of pricing and product categories (see Elevate sections)
   - Activate Button or Card to signup to ODP
- A public or member who clicks Activate Button will go through a custom onboarding to make a plus account
- Highlight sponsored plus account with ODP active account
- /services/plus/odp slug page that plus members can view in both pending and activated vendor status
### APP/SITE/hooks
- onboard/start captures Group/PromoCode
- /services/plus/odp slug page that plus members can view in both pending and activated vendor status
### APIs/SERVICE LAYERS
- Confirmation that says ODP service request is sent and Esther will reach out
- Provide email confirming request (triggered with request creation)
- Send request to Zendesk or **Admin** for EA internal team to complete 

**P1**

- Post activate, an account member can see a deals section with related deals to ODP inside services/ODP/
- Post activate, an account member can see a How to start section with tips and related reads for ODP service
- Post activate, an account member can see a custom Zendesk chat for talking to EA team about questions or issues

## Final Design Files
- [Landing Page Final Design Handoff](https://www.figma.com/file/kG65cs9fawYH42EV2txnj2/%23124-Page%3A-ODP-Landing-Page?node-id=965%3A1917)
- [ODP Slug page Final Design](https://www.figma.com/file/kG65cs9fawYH42EV2txnj2/%23124-Page%3A-ODP-Landing-Page?node-id=1100%3A3003)
- [ODP OB Pathway Final Design](https://www.figma.com/file/joQ05HIfMDGAkLBccM5vpx/%2388-ON-BOARD%3A-Components?node-id=2725%3A52638)

## REFERENCE FILES
- [Vendor Request admin](https://excelerateamerica.retool.com/apps/b3a83d52-4a3f-11ed-a754-1b151ad9be73/Admin-Tools/vendor-account-request)
- [onboard_odp](https://app.diagrams.net/?client=1#G13kKKXHiJImluWPKMfNfCRun5jlOmddXn)
- [onboard_odp preview](https://drive.google.com/file/d/13kKKXHiJImluWPKMfNfCRun5jlOmddXn/view?usp=sharing)
- https://app.diagrams.net/#G14U4Pmi0Bvvgy2ynmeFKDmB_DdCTRR1K2
- https://www.figma.com/file/AIGo6JR4ej82cdymiWlIar/Vendor-Services-Admin?node-id=0%3A1

### ADMIN APP
- [x] excelerate-america/ea-features#180

### HOOKS / SERVICES
- [x] excelerate-america/ea-features#181
- [x] excelerate-america/ea-features#182

####  ODP SERVICE SETUP
- [x] excelerate-america/ea-features#183
- [x] excelerate-america/ea-features#184

#### ODP SERVICE LANDING PAGE 
- [x] excelerate-america/ea-features#185
- [x] excelerate-america/turbo-ea-ecosystem#140
- [x] excelerate-america/ea-features#187
- [x] excelerate-america/turbo-ea-ecosystem#138
- [x] excelerate-america/turbo-ea-ecosystem#137
- [x] excelerate-america/turbo-ea-ecosystem#136
- [x] excelerate-america/turbo-ea-ecosystem#135
- [x] excelerate-america/turbo-ea-ecosystem#134
- [x] excelerate-america/turbo-ea-ecosystem#133

#### ODP SERVICE ONBOARD PATHWAY 
- [x] excelerate-america/turbo-ea-ecosystem#132
- [x] excelerate-america/turbo-ea-ecosystem#131
- [x] excelerate-america/turbo-ea-ecosystem#130
- [x] excelerate-america/turbo-ea-ecosystem#129
- [x] excelerate-america/turbo-ea-ecosystem#128
- [x] excelerate-america/turbo-ea-ecosystem#127

#### ODP SERVICE PAGE SLUG_PENDING
- [x] excelerate-america/turbo-ea-ecosystem#126
- [x] excelerate-america/turbo-ea-ecosystem#143
- [x] excelerate-america/turbo-ea-ecosystem#125
- [x] excelerate-america/turbo-ea-ecosystem#124
- [x] excelerate-america/turbo-ea-ecosystem#123

#### ODP SERVICE PAGE SLUG_ACTIVE
- [x] excelerate-america/turbo-ea-ecosystem#122
- [x] excelerate-america/ea-features#205
- [x] excelerate-america/ea-features#206
- [x] excelerate-america/ea-features#207
- [x] excelerate-america/turbo-ea-ecosystem#141
- [x] excelerate-america/ea-features#208

#### ODP SERVICE FRONT END INTEGRATION
- [x] excelerate-america/ea-features#209
- [x] excelerate-america/turbo-ea-ecosystem#145
- [x] excelerate-america/turbo-ea-ecosystem#120
- [x] excelerate-america/turbo-ea-ecosystem#142

### APIs/SERVICE LAYERS
- [x] excelerate-america/ea-features#173
- [x] excelerate-america/turbo-ea-ecosystem#144
- [x] excelerate-america/ea-features#230
- [x] excelerate-america/ea-features#231
- [x] excelerate-america/ea-ecosystem-admin#110

**Comment by tech-ea** [comment]
### BUsiness Account with Service or vendorAccount:
#### ODP PORTAL
```
{
    ODP: {
	vendorName: Office Depot,
        status: "PENDING",
	type: "PORTAL",
	vendorAccountId: "awaiting odp account number"
	vendorDescription: "this is a OD portal account",
	teamAccountId: bizId
    },
    VENDOR_CODE2: { ... }
}
```
### then ----->
```
{
    ODP: {
	vendorName: Office Depot,
        status: "CONNECTED",
	type: "PORTAL",
	vendorAccountId: "uuuuid from vendor"
	vendorDescription: "this is a OD portal account",
	teamAccountId: bizId
    },
    VENDOR_CODE2: { ... }
}
```
#### ODP BUSINESS (ELEVATE) 
```
{
    OD: {
	vendorName: Office Depot,
        status: "PENDING",
	type: "BUSINESS",
	vendorAccountId: "",
	vendorDescription: "this is a OD Business? account",
	businessAccountId: bizId
    },
    VENDOR_CODE2: { ... }
}
```
------->
```
{
    OD: {
	vendorName: Office Depot,
        status: "CONNECTED",
	type: "BUSINESS",
        vendorAccountId: "uuuuid from vendor",
	vendorDescription: "this is a OD Business? account",
	businessAccountId: bizId
    },
    VENDOR_CODE2: { ... }
}
```

**Comment by tech-ea** [comment]
@davidcjanssens 
I see some milestones but not sure of what day does it need to be launched to the public?

> September 20th, 2022, Pathway Check-in
September 30th, 2022, Preview Landing Page
November (End of Pitch) drive pitch participants to make ODP accounts

**Comment by tech-ea** [comment]
Moved into planned  to discuss TASKS

**Comment by tech-ea** [comment]
@youngmin-ea When you get a minute can we discuss the Handoff design? 
Especially the Responsive Design and card Slider
I started a discussion on [DOCS: Responsive UX & Breakpoints](https://github.com/excelerate-america/ea-ecosystem/discussions/1308)

**Comment by youngmin-ea** [comment]
Added ODP landing page Final Design file link

**Comment by youngmin-ea** [comment]
Added ODP slug pages Final Design file link here ☝️

**Comment by tech-ea** [comment]
@lyndon-bot 

Is this the minimum necessary info to add to BusinessAccount?
```
vendorCode:"ODP",
vendorName: 'Office Depot Partners',
vendorType: 'EXPRESS',
vendorDescription: 'blah',
vendorBusinessAccountId: '1234567',
vendorBusinessAccountCompany: "Bandhan Group Test",
vendorEmail: '[lyndon@excelerateamerica.com](mailto:lyndon@excelerateamerica.com)',
vendorStatus: 'PENDING',

```

```
ODP: {
   vendorCode:"ODP",
   vendorName: 'Office Depot Partners',
   vendorType: 'EXPRESS',
   vendorDescription: 'blah',
   vendorBusinessAccountId: '1234567',
   vendorBusinessAccountCompany: "Bandhan Group Test",
   vendorEmail: '[lyndon@excelerateamerica.com](mailto:lyndon@excelerateamerica.com)'
   // Changed when returned //
      vendorStatus:"CONNECTED",
  // Added to main object when returned //
    vendorAccountNumber: "123254635462351432edwqefgrwvrcax",
    vendorBusinessAccountCompany: "Bandhan Group Test",
    vendorUsername:"lyndonODP",
}
```

**Comment by tech-ea** [comment]
## New monorepo info
### Github 
- REPO: [turbo-ea-ecosystem](https://github.com/excelerate-america/turbo-ea-ecosystem)

### TURBO SITE (Mirror Production)
- SITE_BRANCH: `production` 
- SITE_HOST: [turbo-site-ea-ecosystem](https://vercel.com/excelerate-america/turbo-site-ea-ecosystem)
- SITE_URL: [turbo-ea-ecosystem.com](https://turbo-ea-ecosystem.com)

### TURBO SITE (Mirror Staged)
- SITE_BRANCH: `staged` 
- SITE_HOST: [turbo-site-ea-ecosystem](https://vercel.com/excelerate-america/turbo-site-ea-ecosystem)
- SITE_URL: [turbo-staged.ea-ecosystem.com](https://turbo-staged.ea-ecosystem.com)


### STORYBOOK
- SB_BRANCH: `storybook`
- SITE_HOST: [turbo-story-ea-ecosystem](https://vercel.com/excelerate-america/turbo-story-ea-ecosystem)
- SB_URL: [turbo-docs.ea-ecosystem.com](https://turbo-docs.ea-ecosystem.com)

**Comment by tech-ea** [comment]
## ODP PAges:

The sections and blocks are the same,  but you can view them as static pages:
Temp URLS:
[Landing Page Static](https://turbo-staged.ea-ecosystem.com/services/odp-landing)
[Slug Page Pending](https://turbo-staged.ea-ecosystem.com/services/odp-slug-pending)
[Slug Page Connected](https://turbo-staged.ea-ecosystem.com/services/odp-slug-active)

or this is closer to what it will look like when it's a single URL   but also temp migrating services ...
Temp Dynamic URL:
[business-essentials](https://turbo-staged.ea-ecosystem.com/srvs/business-essentials)

@Slamphier

**Comment by tech-ea** [comment]
### URL to Review: [turbo-staged.ea-ecosystem.com/services/bussines-essentials](https://turbo-staged.ea-ecosystem.com/services/business-essentials)

**Comment by Slamphier** [comment]
Link for slug page: [https://www.odpbusiness.com/] @tech-ea

**Comment by tech-ea** [comment]
## Review Links

### Staged
- codebase: this is the latest code based at branch staged: **turbo-ea-ecosystem.com**
- auth/database the "staged" backend for users firebase project **ea-ecosystem**
- content Hygraph **dev** Environment 
- event / discord bot: **production**
[STAGED: https://turbo-staged.ea-ecosystem.com](https://turbo-staged.ea-ecosystem.com)

### Pre-Production
- codebase: **latest code**  based at branch production: **turbo-ea-ecosystem.com**
- auth/database the **production** backend for users firebase project **ea-ecosystem**
- content Hygraph **Master** Environment 
- event / discord bot: **production**
[STAGED: https://turbo.ea-ecosystem.com](https://turbo.ea-ecosystem.com)

**Comment by tech-ea** [comment]
@excelerate-america/product-team 

### Caveats:
- Not sure what to do about ODP in benefits and explore plus page
- Animations on landing and menu are an experiment in hiding the flash of guest content before user creds load that sometimes happens
- Some layout issues on pre-production  will need to be fixed when we switch over... if fix now they could mess up current site
