### ISSUE TITLE
FEATURE:  Dell Service Pathway

### ISSUE THREAD

**Issue by davidcjanssens** [excelerate-america/ea-features#125]
# FEATURE: Dell Pathway (Landing Page: Dell Plus Service Page & Custom Onboarding to "activate" plus account

## OBJECTIVE
Goal: To amplify our Dell business service beyond benefits but still within plus. To allow direct lead generation and custom onboarding for Dell.

## DEPENDENCIES
- Discussion on 
- excelerate-america/ea-ecosystem#1580 

## TERMS
- **Landing Page:** Public accessible page highlighting feture
- **Pathway:**  Landing Page + Custom Onboard Pathway

## REQUIREMENTS
**P0**

 - [ ] /services/dell-business page that both public and members can view
 - [ ] Service will be Plus and shown in Nav under services
- [ ] Dell page will have:
- - How it works section to highlight the program and benefits
- - Partner/brand logo section
- - Highlights of pricing and product categories 
- - Activate Button or Card to signup to Dell
- [ ] A public or member who clicks Activate Button will go through a custom onboarding to make a plus account
- [ ] Highlight 30-day plus account trial
- [ ] Confirmation that says Dell service request is sent and Esther will reach out
- [ ] Provide email confirming request
- [ ] Send request to Zendesk or admin for EA internal team to complete
- [ ] A plus account who clicks activate Button go straight to a confirmation page Dell service request sent
- [ ] Remove ODP from benefits section and adjust explore plus page

**P1**

- [ ] Post activate, an account member can see a deals section with related deals to Dell inside services/Dell/
- [ ] Post activate, an account member can see a How to start section with tips and related reads for Dell service
- [ ] Post activate, an account member can see a custom Zendesk chat for talking to EA team about questions or issues

## REFERENCE FILES
- figma 
- diagrams

## DEPENDENCIES
Other projects that 

## TASKS
What needs to get done and will be tracked in Tasks 

GanttStart: YYYY-MM-DD
GanttDue: YYYY-MM-DD
