### ISSUE TITLE
FEATURE: Benefits Full Feature ( Slug Page: Page accessible for Plus only that provides description of benefit)

### ISSUE THREAD

**Issue by davidcjanssens** [excelerate-america/ea-features#126]
# Benefit Slug Page: Page accessible for Plus only that provides description of benefit

## OBJECTIVE
Goal: Make it easier to cross sell benefits, making custom onboard for benefits and give more information about benefits to Plus accounts.

## DEPENDENCIES
- Discussion on 
- excelerate-america/ea-ecosystem#1580 

## TERMS
**(Full)Feature:**  A section of the site that  includes an `IndexPage` showing a list of items, and a `SlugPage` or detail page which contains sections and blocks of content and `SideBar` with `SideCards`
**Benefit:** A basic advantage, deal or bonus that a PLUS member can select, claim, use. Can come from EA directly or via a third party company
**Service (Sponsor):**  A series of benefits  from one of our key vendors, that include more than one benefit and has it's own content and info.or A bundle of benefits 
**Service (Bundle):**  A select group of benefits and/or features 

## REQUIREMENTS
**P0**
- [ ] Make Benefits Index a Service that accessible to Public and Members
- [ ] Upon clicking a Benefit card, Public or Member goes through custom onboarding access benefits with Plus Account(see resource flow)
- [ ] Plus Accounts, upon clicking a benefit card, goes to a benefit slug page services/benefits/moo
- [ ] Benefit slug pages will have:
- - Description of benefits (similar to resources)
- - Why the collective likes it section
- - Activate Benefit card/section that sends request to Zendesk 
- - Side bar with related reads, resources

**P1**
- [ ] Benefit Slugs show status of already requested by account

## REFERENCE FILES
- figma 
- diagrams

## DEPENDENCIES
- [FEATURE: ODP Pathway: Landing Page: ODP Plus Service Page with Custom Onboarding to "activate"#124](https://github.com/excelerate-america/ea-features/issues/124)

## TASKS
What needs to get done and will be tracked in Tasks 

GanttStart: YYYY-MM-DD
GanttDue: YYYY-MM-DD
