### ISSUE TITLE
FEATURE: Stripe Subscription Management

### ISSUE THREAD

**Issue by davidcjanssens** [excelerate-america/ea-features#130]
# Stripe Subscription Management

## OBJECTIVE
Have the ability to take payment on subscription fees post trial of plus acccounts

## TERMS
special vocabulary 

## REQUIREMENTS
A plus account should be:
- [ ] able to add a credit card to pay for subscription
- [ ] able to update credit card information if it has expired
- [ ] notified if a payment fails
- [ ] notified if a payment is due when not recurring
- [ ] notified if a payment is pending for recurring
- [ ] able to set payment to be recurring
- [ ] able to pay at a monthly or annual rate
- [ ] able to view a summary of payments 
- [ ] able to receive a receipt via email of payment
- [ ] notified of end of trail 7 days prior
- [ ] notified of close of account 14 days after end date of trail or payment period
## REFERENCE FILES
- figma 
- diagrams

## DEPENDENCIES
Other projects that 

## TASKS
What needs to get done and will be tracked in Tasks 

GanttStart: YYYY-MM-DD
GanttDue: YYYY-MM-DD
