### ISSUE TITLE
TOOL: Mixpanel Integration

### ISSUE THREAD

**Issue by tech-ea** [excelerate-america/ea-features#17]
## TOOL: Add Mixpanel and Integrate
- [ ] excelerate-america/ea-ecosystem#1244
- [x] excelerate-america/ea-ecosystem#1243
- [x] excelerate-america/ea-ecosystem#1242
