### ISSUE TITLE
UPDATE: ELEVATE ADJUSTMENTS

### ISSUE THREAD

**Issue by tech-ea** [excelerate-america/ea-features#175]
# ELEVATE ADJUSTMENTS

## OBJECTIVE
Improve onboarding of Elevate and remove popup on articles to allow better testing and see if express users actually want our deals.  

Background: Based on recent data, nearly 1700 users have hit OB1 but there is signficant drop off on the form.  Two theories: 1) Improved onboarding more like Excelerate would help communicate steps.  2) removal of popup and status checks would allow users to see more content.  

## TERMS
special vocabulary 

## REQUIREMENTS
- [ ] Improve onboarding to match/replicate EA.com, potentially using a custom onboard for signup and creditials on both Elevate and EA.com
- [ ] Eliminate pop-up and only make status check on cashback claim button.  This will allow public to get deals on links but for this test that is okay
- [ ] Scrub language that says we payout quarterly or via ach.  Instead say we payout in gift cards once certain balance thresholds are met.  
- [ ] Remove BENEFITS and host only on EA.com. Potentially reference benefits page or Plus via EA.com

Experiments to run:
- [ ] reach out to ~300 users who attempted onboarding to see if they would try again
- [ ] test to see if Express users want ODP deals or are interested in other deals such as Dell

## REFERENCE FILES
- figma 
- diagrams

## DEPENDENCIES
Other projects that 

## TASKS
What needs to get done and will be tracked in Tasks 

GanttStart: YYYY-MM-DD
GanttDue: YYYY-MM-DD

**Comment by tech-ea** [comment]
I included a link to this issue from the Sunset PLan Issue
- #174  
so it can be referenced
