### ISSUE TITLE
ADMIN: EA_ECOSYSTEM  STAGED -> PROD

### ISSUE THREAD

**Issue by tech-ea** [excelerate-america/ea-features#176]
# ADMIN: EA_ECOSYSTEM  STAGE -> PROD 

## OBJECTIVE
Seperate all services into separate projects PROD and STAGE to better dev, test, secure manage etc..

ADMIN: EA_ECOSYSTEM  STAGE -> PROD

## TERMS
Staged: staged-ea-ecosystem 
Production: ea-ecosystem

## REQUIREMENTS
- Create a GCP project that can emulate the current back-end setup of the ea-ecosystem application 

## QUESTIONS
- What parts should we migrate 1st 

## RISKS
- Deploys will no be hot fixes, extra steps involved with deploying updates

## REFERENCES

- https://firebase.google.com/docs/projects/dev-workflows/overview-environments
- https://medium.com/@alifyandra/how-i-separate-development-environments-on-firestore-cf512a6afb7b
- https://javascript.plainenglish.io/handling-different-environments-in-firebase-apps-7c1c50708ffd
- https://www.firebaseconsulting.com/feature/2019-07-20-firebase-environments
- https://techblog.geekyants.com/integrating-a-cicd-pipeline-using-github-actions

## TASK (These are visible here but tracked in the TASKS project )
- [ ] excelerate-america/ea-ecosystem-admin#105
- [x] excelerate-america/ea-ecosystem-admin#104
- [x] excelerate-america/ea-ecosystem-admin#106
- [x] excelerate-america/ea-ecosystem-admin#107
- [x] excelerate-america/ea-ecosystem-admin#108
- [x] excelerate-america/ea-ecosystem-admin#109
- [x] excelerate-america/turbo-ea-ecosystem#121

**Comment by tech-ea** [comment]
Firebase console:
https://console.firebase.google.com/u/0/project/staged-ea-ecosystem/settings/general
