### ISSUE TITLE
FEATURE:  PLUS Account Settings & Stripe

### ISSUE THREAD

**Issue by tech-ea** [excelerate-america/ea-features#19]
# Stripe Subscription Management

## OBJECTIVE
Have the ability to take payment on subscription fees post trial of plus acccounts

## TERMS
special vocabulary 

## DEPENDENCIES
- Discussion on 
- excelerate-america/ea-ecosystem#1580 

## REQUIREMENTS (Account Plus)
A plus account should be:
- [ ] able to add a credit card to pay for subscription
- [ ] able to update credit card information if it has expired
- [ ] notified if a payment fails
- [ ] notified if a payment is due when not recurring
- [ ] notified if a payment is pending for recurring
- [ ] able to set payment to be recurring
- [ ] able to pay at a monthly or annual rate
- [ ] able to view a summary of payments 
- [ ] able to receive a receipt via email of payment
- [ ] notified of end of trail 7 days prior
- [ ] notified of close of account 14 days after end date of trail or payment period

## REQUIREMENTS Stripe
P0
- [ ] Every Plus Account Signup starts with a trial. There are 2 trial levels
- 30 day trial --> Default trial for non community partners or non vendor partners or "off the street"
- 1 year trial --> Community partners and other groups who are provide a special link and promo code

- [ ] Every Plus Account after a trial ends will be place into one of two paid levels
- Paid --> Monthly or Annual membership that can be set to recur via Stripe
- Sponsored --> Monthly or Annual membership that is covered by partners and does not need Stripe (ie OD Express)

Details of Plus Account:
- [ ] A 30 day trail or 1 year trial or paid membership can be changed to a sponsored trial at any point
- [ ] The first member to signup for plus will become the owner of the account
- [ ] 7 days prior to ending of a trial or paid membership, an account owner should receive an email notification to:
- Trial --> Add Credit card info to Stripe
- Paid recurring --> Be notified their credit card ending in XXXX will be charged $XXX on X Date
- Paid non recurring --> Be notified their membership will end if payment is not made by X Date
- Sponsored ending --> Add Credit card info to stripe and select monthly or annual and recurring
- [ ] Between 7 days prior to ending trial or paid membership and 14 days after end date if update not made, owner of account should:
- receive additional emails reminding them to update account or credit card
- be prompted in app to update subscription information
- lose plus access after 14 days
- delete plus data after 60 days
- [ ] Plus Account subscription is $149 yearly or $15 monthly
- [ ] Plus Account payment is handled by Stripe and can receive Visa/Mastercard, notify users when credit needs updating, notify users when payment has been made, provide a history of invoices of payment
- [ ] Non Plus members should not be able to access the Account page.  It should not be shown in Nav for member
 
- [ ] The owner of the account can:
- Add a credit card and receive receipts with Stripe
- Edit Account information and email subscriptions
- Delete/end Plus account
- Invite up to 10 other members to their account (P1)
- Remove members from the account (P1)
- Change ownership to another member (P1)
- (if Elevate continuees) Add bank account information to Dwolla for cashback (P1)

P1
- [ ] Account page includes Activity of the account including benefits used/claimed, deals claimed
- [ ] Benefit cards/page would indicate which benefits have been requested by a member of the account
- [ ] Benefits index page can be seen by members without Plus account but if clicked will be prompted to signup to Plus
- [ ] Custom onboarding flows for plus including Benefit clicks, Cashback/Elevate program and general Plus signup

- [ ] A member of the account can (P1):
- Request or access all benefits
- Claim cashback or coupon deals
- View Account Information but not edit
- View Cashback activity page and balance

## RISKS
- Potential scope creep...
- 

## REFERENCE FILES
- figma 
**(Members/Accounts)**
https://app.diagrams.net/#G19OdSZoKLJFC06TtMDq7b2XdGNLZlJFzg 
- Levels to Plus ACCOUNT
https://github.com/excelerate-america/ea-ecosystem/discussions/774

## TASKS
What needs to get done and will be tracked in Tasks 

GanttStart: YYYY-MM-DD
GanttDue: YYYY-MM-DD

**Comment by davidcjanssens** [comment]
@tech-ea @lyndon-bot @Slamphier @youngmin-ea 

Dropped above requirements in for Plus

**Comment by tech-ea** [comment]
@youngmin-ea To what extent is this in design?

**Comment by youngmin-ea** [comment]
> @youngmin-ea To what extent is this in design?

@tech-ea it's more related to #4 which is Profile page, Account settings + membership status
