### ISSUE TITLE
TOOL: EA Admin APP (Name TBD)

### ISSUE THREAD

**Issue by tech-ea** [excelerate-america/ea-features#23]
# EA Admin APP

## OBJECTIVE
A web app for the internal team  to view, edit, and delete data in ea-ecosystem databases. The data includes members data, events, ect...

The App should also allow for creating reports based on queries in addition the apps tables should, contain shortened views of backend data formatted to be understood by non engineers

## TERMS
- **Retool Naming structure:** [Feature] - [Action/Modifier] - [Location]
- **Retool Folders:** 

> 1. Admin Tools: Contains dashboards and tools designed to be used by both engineering and non engineering member of EA 
> 2. Elevate Tools:  Contains dashboards and tools designed to be used by engineering team members, contents of the folder relates specifically to the Elevate Product 
> 3. Internal Tools: Contains dashboards and tool designed to be used by engineering team members, majority of the contents refer to the management of the `ea-ecosystem` and `excelerate-app` firebase projects 
> 

- **Reports:** Counts, Charts, Graphs or other visualizations made from data resources
- **Views:** Tables containing information from data resources 
- **Actions:** Functions triggered by user actions that (creates,updates or deletes) from data resources

### Membership Collection

**Reports:**
- Show count of unique members within EAX without internal users and test accounts 

**Views:**
- Show connected discord accounts without internal users and test accounts 

**Actions:**

###  Events Collection

**Reports:**

**Views:**
- View RSVPS by Event with member emails and discordids 
- Ability to Display Upcoming events with a start time in human readable and rvsped members  

**Actions:**
- Ability to create past events 

###  Groups Collection 

**Reports:**

**Views:**

**Actions:**
- Ability to create groups 
- Ability to update groups

### Business Account Collection

**Reports:**
- Show the count of business accounts within EAX 

**Views:**

**Actions:**
- Ability to change the `subscription status` of a given business account
- Ability to update a business account to contain `vendor accounts`

## RISKS
- possible issues/scope creep

## REFERENCE FILES
- Collections: 
https://app.diagrams.net/#G1P1Lktor8gjP-7RXqX_yOrkucPpnxUb1u
- Admin Tools Dashboard:
https://excelerateamerica.retool.com/apps/Admin-Tools/admin-panel-ea-eco-system
- Past Event Creation Dashboard: 
https://excelerateamerica.retool.com/apps/Admin-Tools/events-past-add-ea-connect-bot
- Groups Dashboard:
https://excelerateamerica.retool.com/apps/Admin-Tools/group-promo-add-ea-ecosystem

## DEPENDENCIES
Other projects that 

## TASKS

- [x] Build Members Table (Filter By hasDiscordId, hasBusinessAccount, )
- [x] Build Events Table show RsvpList
- [ ]  **Admin** for EA internal team to complete business account setup for ODP & Dell Landing Page

### Membership
- [x] Show count of members within EAX without internal users and test accounts 
- [x] Show connected discord accounts  without internal users and test accounts 

###  Events
- [x] View RSVPS by Event with member emails and discordids 
- [x] Ability to create past events 
- [x] excelerate-america/ea-ecosystem-admin#90

### Business Accounts
- [ ] Show count of business accounts within EAX 
- [ ] Ability to change the subscription status of a given business account

**Comment by bandhanEA** [comment]
https://excelerateamerica.retool.com/editor/dev-bandhan-eco-system-admin-panel

**Comment by davidcjanssens** [comment]
Main question:  What do you show to an internal user of this admin?  I know we say show member count, which is a number but if we show a table of members or make it easy to lookup a member based on email or ID, then what does an internal user see?  I don't think tis the whole backend table.
