### ISSUE TITLE
FEATURE: 

### ISSUE THREAD

**Issue by tech-ea** [excelerate-america/ea-features#247]
# LAUNCH MONOREPO V2 (with new SERVICE ODP)

## OBJECTIVE
Replace current monorepo  with upgraded turborepo which includes the new services ODP onboard pathway & services/business-essentials landing & slug page

## DEPENDENCIES
- turbo repo project
- services ODP project

## REQUIREMENTS
- Merge/replace ea-ecosystem repo with  forked branch turbo-ea-ecosystem 
- 

## QUESTIONS
- Which would be better : 
1.  merge forked branch back into main branch
2. Convert forked branch to main and reroute domains to new Vercel projects.

## RISKS
- possible issues / scope creep

## REFERENCE FILES
- figma 
- diagrams

## TASKS
- [ ] QA turbo-staged.ea-ecosystem.com
- [ ] UPDATE HyGraph `Master Environment`  to match  HyGraph `dev Environment`
- [ ] MIGRATE new content on HyGraph `dev environment` to H
