### ISSUE TITLE
PROJECT: OD CALC REBATES Q3 2022

### ISSUE THREAD

**Issue by tech-ea** [excelerate-america/ea-features#255]
# OD CALC REBATES Q3 2022 

## OBJECTIVE
Create the Od Calc Rebate report for Q3 2022

## TERMS
special vocabulary 

## Google Drive
- [DRIVE OD PAYMENTS](https://drive.google.com/drive/folders/1jh4rEieLvqLgJ12LW65bLmpLLjTwpmN7?usp=share_link)
- [MASTER AFFILIATES SHEETS](https://docs.google.com/spreadsheets/d/14iSYcQ81XR5ZjpbthfZKr2M69YsvYe0M5CkXag1GFCk/edit#gid=1893340737)

### Storage

- [BUCKET:od-rebate-calc-in](https://console.cloud.google.com/storage/browser/od-rebate-calc-in?project=od-calc-lake)

### BigQuery
- [DATA_SOURCE:OD_CALC_LAKE](https://console.cloud.google.com/bigquery?project=od-calc-lake&ws=!1m0)

### DataStudio
- [2022 Q3 RebateReport 1110](https://datastudio.google.com/s/osGSga0aBrs)

![Image](https://user-images.githubusercontent.com/52209730/201238345-384980d7-3d8b-4859-8118-c85e68efe6b4.svg)

## TASKS
# Steps to build OD Quarterly  Rebate Report
- [ ] Upload Excel file to Folder 'Corporate / Office Depot / Rebate Reports'
- [ ] Save as Google Sheet and Rename to OD_YYYY_Qn_SOURCE
- [ ] Duplicate Tab 'Main Report' and rename YYYY_Qn_Main
- [ ] For new Tabs: Remove Extra Header Rows, Remove Total Row, Remove Blank Columns and Remove Blank Rows
- [ ]  For new Tabs: Rename Column Headers and Change the Column Number Formats as outlined above in the Details section of this card
- [ ] Before Exporting! MANUALLY CHANGE PARENT IDs for Accounts identified above (See in details above)
- [ ] For new tabs: Download Current Sheet as .CSV
- [ ] GCS> Upload file: OD_YYYY_Qn_SOURCE-YYYY_Qn_Main.csv to GCP Bucket: od-rebate-calc-in/YYYY/
- [ ]  BigQuery> Create a new Tables in od-calc-lake.od_rebate_in.qtr_tables dataset by importing csv from GCS storage bucket (see attachment below for settings)

## Update Master Lists [MASTER AFFILIATES](https://docs.google.com/spreadsheets/d/14iSYcQ81XR5ZjpbthfZKr2M69YsvYe0M5CkXag1GFCk/edit?usp=sharing)
- [ ] Add / Update Current Quarter Master Affiliates sheet
- [ ] Add / Update current Quarter DUES sheet
- [ ] Add / Update current Quarter ACH_DETAILS
- [ ] Add / Update current Quarter Check_DETAILS

## Create Data Table Sources
- [ ] YYYY_Qn_MissingMasters
- [ ] YYYY_Qn_RawData 
- [ ] YYYY_Qn_DataByParent
- [ ] YYYY_Qn_ACH_Payments
- [ ] YYYY_Qn_Check_Payments

## CreateReports
- [ ] YYYY_Qn_MissingMasters 
- [ ] Recreate Source data  when All Masters are accounted for
- [ ] YYYY Qn-1 RebateReport_MMDD - Duplicate Previous Report in [DataStudio](https://datastudio.google.com/u/0/navigation/reporting)
- [ ] Replace Qn-1 with Qn data
- [ ] Share YYYY Qn RebateReport_MMDD

Grandparents
----
2005 EA Chamber Communities
2014 EA Commerce Elite
2015 EA Express

## File Naming COnvention

Source File From OD:
`OD_YYYY_Qn_SOURCE`
`YYYY` = Year (example: 2020)
`Qn` = Quarter on of the following Q1,Q2,Q3,Q4

## Sheet Column Names / format
```
GRANDPARENT_ID: INTEGER
GRANDPARENT_NAME: STRING
PARENT_ID:  INTEGER
PARENT_NAME: STRING
OD_ACCOUNT_ID:  INTEGER
OD_ACCOUNT_NAME: STRING
SALES_TOTAL: FINANCIAL (FLOAT)
SALES_15: FINANCIAL (FLOAT)
SALES_65: FINANCIAL (FLOAT)
REBATES_TOTAL: FINANCIAL (FLOAT)
REBATES_15: FINANCIAL (FLOAT)
REBATES_65: FINANCIAL (FLOAT)
```

Steps
[Delete](https://trello.com/c/502a5JZj/89-od-calc-lake-source-data-ingest#)
0%
Upload Excel file to Folder 'Corporate / Office Depot / Rebate Reports'
Save as Google Sheet and Rename to OD_YYYY_Qn_SOURCE
Duplicate Tab Existing Detail and rename YYYY_Qn_Existing
Duplicate Tab Migrated Detail and rename YYYY_Qn_Migrated
For both new Tabs: Remove Extra Header Rows, Remove Total Row, Remove Blank Columns and Remove Blank Rows
For both new TABS: Rename Column Headers and Change the Column Number Formats as outlined above in the Details section of this card
Before Exporting! MANUALLY CHANGE PARENT IDs for Accounts identified above (See in details above)
For both TABS: Download Current Sheet as .CSV
GCS> Upload file: OD_YYYY_Qn_SOURCE-YYYY_Qn_Existing.csv to GCP Bucket: od-rebate-calc-in/YYYY/
GCS> Upload file: OD_YYYY_Qn_SOURCE-YYYY_Qn_Migrated.csv to GCP Bucket: od-rebate-calc-in/YYYY/
BigQuery> Create a new Tables in od-calc-lake.od_rebate_in.qtr_tables dataset by importing csv from GCS storage bucket (see attachment below for settings)
## MANUALLY CHANGE PARENT IDs
2014 EA Commerce Elite
----
CHANGE:
700597 G S COSMECEUTICAL USA INC 700597 is under Elite Parent and needs to be a parent
```
2014	EA Commerce Elite	700597	G S COSMECEUTICAL USA INC
```

9799878 SOUTHWOOD REALTY needs to become a parent under ELITE GP
```
2014	EA Commerce Elite	9799878	SOUTHWOOD REALTY	9799878
```
~~34316676 WYATT FIELD SERVICES needs to become a parent under ELITE GP~~

~~29314805 H M T is under Elite parent as a child account and needs to be paid as a parent.~~
Add these as parent in raw:

15011910	CRC WAREHOUSING N CAROLINA LLC
~~48184319	MD BLDG PRODUCTS	48184319	MD BLDG PRODUCTS~~
RENO needs to update sponsorship to $0
