### ISSUE TITLE
FEATURE: EAX User Admin (ea-ecosystem & staged-eac-ecosystem)

### ISSUE THREAD

**Issue by tech-ea** [excelerate-america/ea-features#257]
# EAX User Admin (ea-ecosystem & staged-ea-ecosystem)

## OBJECTIVE
Remove orphaned accounts and incomplete accounts both  users and member records
standardize account  purge processes for both internal test accounts and real accounts
setup rolling inactivate anonymous auth user removal

## TERMS
**authenticated account**  a user credential saved in firebase auth server
**anonymous auth account**  an anonymous credential saved in firebase auth server
**orphaned auth account**: authenticated users that had member records removed
**incomplete accounts**: account/member  that had team accounts / auth removed 

## QUESTIONS
Where is the best place to store the documentation for these processes that require external tools and may require external team members? github wikiw? retool docs, discussion?

## DEPENDENCIES
Other projects that 

## REQUIREMENTS
-  Create / Modify a single trigger that removes the authenticated account and all related records.
-  Should probably use firebase admin SDK, to make sure subcollections are also removed
-  Should have a log of what was removed 

## RISKS
- no time

## REFERENCE FILES
- [Firebase subcollection delete](https://firebase.google.com/docs/firestore/solutions/delete-collections?authuser=0&hl=en)
- [Firebase Authentication with Identity Platform](https://firebase.google.com/docs/auth?authuser=0#identity-platform)
- [Firebase Identity anon clean up](https://firebase.google.com/docs/auth/web/anonymous-auth?hl=en&authuser=0#auto-cleanup)
## TASKS
- [ ] Identify all orphaned auth accounts and batch remove them.
- [ ] Identify any incomplete member accounts and remove them
- [ ] Modify `triggerRemoveInfo` function located `functions/src/firestore/triggers.ts` 
    - [ ] Single trigger that removes the authenticated account and all related records
    - [ ] Add adminSDK so removal can also delete subcollections
    - [ ] should also save a file with the results of the operation
- [ ] Setup / activate Firebase Authentication with Identity Platform and Automatic clean-up
- [ ] Update Retool App
- [ ] Document process

**Comment by sanbeaman** [comment]
@lyndon-bot hi
