### ISSUE TITLE
PROJECT:  Short Term Site Optimization 

### ISSUE THREAD

**Issue by tech-ea** [excelerate-america/ea-features#281]
# PROJECT:  Short Term Site Optimization to get better COre Web Vitals

## OBJECTIVE
Update and/or refactor certain key aspects of the Site to get a better score on Core Web Vitals

## TERMS
COre Web Vitals

## DEPENDENCIES
- #277 

## REQUIREMENTS
- [ ] Add robots.txt https://vercel.com/robots.txt
- [ ] Add Sitemap 
- [ ] Optimize the current **LandingPage**  code and content for SEO, Analytics, etc...
- [ ] test  all the current analytics services and tools against ads and landingPages

## QUESTIONS
- How many different types of images are there through out Site.
- 

## RISKS
- possible issues / scope creep

## REFERENCE FILES
- figma 
- diagrams

## TASKS
- [ ] Update Next/Image Component from (v12 to v13)
- [ ] List and define how we use Images across Pages, Sections, Blocks, Cards and Panels
- [ ] Update the Current Image Component to account for all these variations and/or
- [ ] Create new Specialized Image Components for each of these Image variations
- [ ] Define the process and tool set for managing Assets from source file to CMS
- [ ] Remove unused / duplicate image assets from Staged and Master Hygraph
