### ISSUE TITLE
PLATFORM: OMNIBUS

### ISSUE THREAD

**Issue by tech-ea** [excelerate-america/ea-features#297]
# PLATFORM: OMNIBUS  
EA's Contact and Customer Data Platform

## IDEAS
Get the Contacts Sorted - Everything we do revolves around our ability to communicate to the right people, the right message at the right time. Right now it’s an embarrassing mess. Our centralized home for all contacts with unique EA IDs will be referred to as the Omnibus.
Get Data Going - All our future value props related to ODP revolve around data. It drives future features, smart communications, and new marketing opportunities. We also need data to see how the business is doing - i.e.- who are we getting paid for, how many accounts, who is new and where are we losing.
Get Our Pipeline Pumping - Our pipeline is how we take a customer from prospect to money, becoming members along the way. Much of our plans and projects should be centered around moving people through each stage of the pipeline.

## OBJECTIVE
(Distill all ideas into clear, measurable, and actionable objectives

## TERMS
special vocabulary 

## DEPENDENCIES
- [ ] DOMAIN SPECIFIC VOCABULARY

### Define and Diagram the OMNIBUS & SOCIUM

- [ ] DATA DEPOSITS: List  all the current data deposits include format, fields, size, and frequency.
- [ ] INPUTS: Define all the ea internal services and external (3rd party) services  that send data to the  OMNIBUS
- [ ] OUPUTS: Define all the ea internal services and external (3rd party) services that receive data from the  OMNIBUS

- [ ] COMPANY NEEDS: Define how the company will use the OMNIBUS
    - How do we send email campaigns to correct people
    - How do we run a report
    - How do we use the results of a report in another app
- [ ] DATA FACTORS: 
    - Data Model
    - QueryPerformance
    - Scalability
    - Durability
    - Ease of Use
    - Cost

- [ ] TECH CONSTRAINTS 
    - Current skill sets (nodejs, php, python, go....
    - Vendor lock-in (GCP, Snowflake, etc)
    - 

- [ ] EXTERNAL/OTHER CONSTRAINTS?
    - IMportant milestones / dates
    - Monthly Budget cap
    - Security requirements
- [ ] EVALUATE Off-the-shelf Solutions (if any)
- [ ] SOLUTIONS: Propose atleast 2 possible SOLUTIONS to the problem
    - DataModel and Architecture
    - Programming Language
    - Database Source System
        - traditional ,event-sourced, command-sourced, CQRS, Snapshot
    - Related Design Pattern
        - (Request-response design, Event-driven design, Polling design, pubsub design,  Batch processing design)
    - Database Technology (SQL, NoSQL, Graph, etc)
    - Database Vendor (GCP, Snowflake, etc)
- [ ] Analyze the SOLUTIONS, pros / cons , cost, etc
- [ ] Select a SOLUTION and Create RoadMap 

## QUESTIONS
List any questions concerning requirements or objective

## RISKS
- possible issues / scope creep

## REFERENCE FILES
- figma 
- [Omnibus Draft](https://drive.google.com/file/d/1hjK-vSEX_OA7C11urwbYnSjwBx4TKh8r/view?usp=sharing)

![Image](https://user-images.githubusercontent.com/80287668/211039935-763e903e-1f7f-432f-9dc6-a189cc992dd4.png)

## TASKS
What needs to get done and will be tracked in Tasks
