### ISSUE TITLE
FEATURE: MEMBERSHIP PROFILE

### ISSUE THREAD

**Issue by tech-ea** [excelerate-america/ea-features#4]
# Membership Profile

## OBJECTIVE
A page visible to the member to display and edit their member details.

## TERMS
special vocabulary 

## REQUIREMENTS
P0
### Profile Page

- Private Profile page for member that can be edited (except for email)
- Profile will be created after member signs up via any onboard pathway. 
- Discord does not need to be added
- Section that includes member details:
    - first/last name, 
    - email (not editable), 
    - password editable via reset password process
    - bio, 
    - website link,
    - social links
- Section includes Discord Details once a member has connected Discord via OAuth 
    - discord name (not editable in app)
    - image to profile (not editable in app)
- Section that has an "Upgrade to Plus" CTA (similar to homepage) that changes once signed up to has "Manage your Plus Account" CTA that directs user to Account page

### NavBar Update
- Logged In Nav that includes "Avatar" image of profile and provides a drop down nav of Profile, Account (or Explore Plus) and Sign Out

P1
- Section that includes Discord data from #starthere channel including skills, looking for, company stage
- Section that includes "Your upcoming events" which shows a user events they have RSVP'd for
- Sub navigation that jumps user to index points on the page to reduce scrolling
- Ability to show Community Partner name that member is connected to (if applicable)?
- A place to remove themselves from the collective
- a notifications / unsubscribe
P2
- Section that includes "contributions" pulled from data in discord and app including "Events Attended", "Sparks Created", and "Member Matches"

## RISKS
- 

## REFERENCE FILES
[**(Collections Diagram)**](https://app.diagrams.net/#G1P1Lktor8gjP-7RXqX_yOrkucPpnxUb1u)
[FIGMA ](https://www.figma.com/file/RwCv9NLTzBTA02kneJlJRb/Wireframe%3A-Resource-%26-Profile-%26-DiscordLanding?node-id=850%3A2464)

## DEPENDENCIES
excelerate-america/ea-ecosystem#1259 
excelerate-america/ea-features#23 
## TASKS

~~Account Home Page (see Figma)~~

~~Create Account Home Page with 2 sections (Profile Settings, and Settings for Plus)~~

**Private Profile Page (see Figma)**

- [ ] Create a Membership Details Section (Individual Editing View)
- [ ] Create a Membership Details Section (Individual Default View)
- [ ] Create Profile Left Side Bar
- [ ] Create a Member Card consisting of a Profile Picture, Display Name, and Discord ID (Oauth2 shows a discord avatar picture or general image [retry] ) 
- [ ] Build Member Details Collection to hold (bio, challenge, website link, social links) (see Draw.io)
- [ ] Request Discord Data:  Business Stage, Go-to-Skills and Looking For from the `discord guild member api`
- [x] https://github.com/excelerate-america/ea-ecosystem/issues/1259
- [ ] Update Logged In Nav to include profile avatar and a drop-down nav of Profile, ~~Account (or Explore Plus)~~ and Sign Out
- [ ] Onboarding Pathway to add discord on profile page (variation community onboarding pathway)

GanttStart: YYYY-MM-DD
GanttDue: YYYY-MM-DD

**Comment by davidcjanssens** [comment]
@tech-ea @lyndon-bot @youngmin-ea @Slamphier 
Updated the Profile requirements above.  

@Slamphier can you mirror this for Discord page

**Comment by tech-ea** [comment]
@Slamphier What fields on profile will be pulled from discord and what fields will be accessed from  database?
