### ISSUE TITLE
FEATURE: Grant Competition Landing Page & Onboard Pathway

### ISSUE THREAD

**Issue by tech-ea** [excelerate-america/ea-features#63]
Marketing and Market Dev would like to run another Pitch competition with annoucement and starting of submission beginning the week of August 29th.  The requirements to submit will be a user must be a member (no discord necessary).  

We would like to create a Pitch competition landing page that the public can see but when signed in as a member shows a section for submission via a TypeForm type link.  (Could be a custom form but we should discuss scope)

LAUNCH 08-29-2022

## Requirements

- Public landing page with CTA to signup as member to submit
- Custom onboarding to track who is signing up for intent to submit
- Landing page will include sections describing the competition, timeframes and rules.  It will also higlight events that we will run during the submission time period to help support members creating their submissions
- Member signed view will need to provide section to submit their entry (link or custom form)
- Entry submission will include text fields, multiple choice or dropdown selections and ability to add link or file for a short video
- Entries can go to a google sheet and ideally we can connect the Member ID to these entries (not necessary)
- Landing page post submission end date should remove entry section and add section that date is closed...
- Once the application period is over, some blocks will be swapped to new blocks; Voting, Judges, and Live Event link - will update the design file and notify @sorengrey 
- On Homescreen, the Grant competition card should replace "Recent Activity" 
- Add `Grant Competition` under the `Services` nav menu and link to this page -- this link should comes first in the nav menu
- URL of this page: excelerateamerica.com/services/grant-competition 

## Design Files

[Grant Landing Page Design handoff](https://www.figma.com/file/uvnNQkkiRqH7MOJUKM9Jpi/%2363-Grant-Competition-Landing-Page?node-id=42%3A1535)
This includes:
- Default Design for Desktop version w/ spacing info
- Responsive views
- Card component for Homepage

## Application form & iframe code

[Application Form in Google form](https://forms.gle/mpcnrPcbXc92TCga6)
```<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSfRRvCzu_BDaK-zKbdMzVzYejY9hW6VXIL8Q6TXqPToeJedZg/viewform?embedded=true" width="640" height="2134" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>```

## Tasks to Complete

- [x] Export and upload all new assets
- [x] Build page in Hygraph with existing components
- [x] Build new hero block, "Grant Hero Block"
- [x]  Build new Checklist Block
- [x]  Build new block for Thank You section
- [x]  Create new dark green Section LayerStyle
- [x]  Build Grant Landing Page  on DEV
- [x]  Build out Grant Landing Page in Master
- [x]  Build **OnboardPathway**  `member-grant` 
- [x]  Build **OnboardPage** `member-grant` START
- [x]  Build **OnboardPage** `member-grant` FORM (signup)
- [x]  Build **OnboardPage** `member-grant` FORM (google form entry)
- [x]  Discuss viewing Entries

**Comment by youngmin-ea** [comment]
@tech-ea @sorengrey Landing page design for launching is done, so shared the handoff file above.

**Comment by tech-ea** [comment]
see https://github.com/excelerate-america/ea-features/issues/132
