### ISSUE TITLE
FEATURE: Discord Landing Page

### ISSUE THREAD

**Issue by tech-ea** [excelerate-america/ea-features#8]
## Requirements:

P0
- [x] Integrate widget bot in page iframe
- [x] How to use discord/utilize
- [x] How to set up a profile
- [x] Go to this channel and do this... Call to action

P1
- [ ] Potentially add what each channel does/talks about
- [ ] How to use emojis, screen grabs, gifs, reactions
- [ ] input popover widget in app after ob2

## Tasks
- [x] #66
- [ ] #67
- [x] #68
- [x] #69
- [x] #70
- [x] #71
- [x] #72
- [x] #73
- [x] #74

## Design Files
[Figma Designa Handoff File](https://www.figma.com/file/ORoB1V1if5GoGZe46sj4cF/%238%3A-Discord-Landing-Page?node-id=42%3A1535)

## References:
https://docs.widgetbot.io/embed/html-embed/tutorial/

**Comment by davidcjanssens** [comment]
@Slamphier Can you add above a set of requirements/bullets for discord page.

**Comment by davidcjanssens** [comment]
@Slamphier can you add places we expect to link this page to on the site?  ie Footer, ? areas for discord cards, in events etc

**Comment by youngmin-ea** [comment]
@tech-ea @davidcjanssens @lyndon-bot @sorengrey @Slamphier Added design handoff. Also, this page would be on footer only as named "About Discord"

**Comment by sorengrey** [comment]
I have created a diagram of what components/etc. we will need. It should give us an idea of what we need to create, and what we already have to leverage.

https://www.figma.com/file/EcjpKMigt6rYP16QQpeUOl/Discord-Landing-Diagram?node-id=0%3A1398

**Comment by sorengrey** [comment]
@lyndon-bot @tech-ea
I've hit a roadblock on building the section with the channel cards. I need a Channel ID and a Guild ID for each card. But the #build-profile channel doesn't exist yet.

Also, I'm not sure where to look up the other channel IDs.

**Comment by youngmin-ea** [comment]
@tech-ea @sorengrey Can we move this Discord Landing page under `Services` with the title as `CONNECT IN DISCORD`?

**Comment by sorengrey** [comment]
@youngmin-ea Yes, I can change this

**Comment by youngmin-ea** [comment]
@sorengrey Since we include this landing page as "Connect in Discord" in Services, we don't need to put them on the footer. Can we remove it from the footer?

**Comment by tech-ea** [comment]
see [FEATURE: Discord Interactive Widget](https://github.com/excelerate-america/ea-ecosystem/issues/986) for widget
